---
params:
  thresh: 
    low: 0.2
    high: 0.6
  exp: 
    low: 0.0
    high: 1.5
  slope:
    low: -2
    high: 2
  mean: 
    low: 0.3
    high: 0.8
  std: 
    low: 0.6
    high: 1.0
  circFactor:
    low: 0.3
    high: 0.6
  grid: 
    hY:
      low: 3
      high: 6
    wX:
      low: 3
      high: 5
  hskew: 
    low: 0.3
    high: 0.6
  wskew: 
    low: 0.1
    high: 0.2
  invert: False